#!/bin/bash

DOCKER_BUILDKIT=1 docker build --progress=plain \
  --build-arg COMMIT=$(git rev-parse HEAD) \
  --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  --build-arg VCS_URL=$(git config --get remote.origin.url) \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --build-arg ALPINE_VER="${ALPINE_VER}" \
-f $DOCKERFILE_PATH \
-t $IMAGE_NAME .
